allowBuilds:
  dtrace-provider: false
  protobufjs: false

packages:
  - "."

overrides:
  "@xmldom/xmldom": "0.8.13"
  "brace-expansion@1.1.12": "1.1.13"
  "brace-expansion@5.0.4": "5.0.5"
  flatted: "3.4.4"
  lightningcss: "1.33.0"
  lodash: "4.18.1"
  node-forge: "1.4.0"
  "picomatch@2.3.1": "4.0.7"
  "picomatch@4.0.3": "4.0.7"
  postcss: "8.5.10"
  "xcode>uuid": "14.0.2"
  yaml: "2.9.0"
