allowBuilds:
  dtrace-provider: false
  protobufjs: false

packages:
  - "."

overrides:
  "@xmldom/xmldom": "0.8.13"
  "brace-expansion@1.1.12": "1.1.13"
  "brace-expansion@5.0.4": "5.0.5"
  flatted: "3.4.2"
  lightningcss: "1.30.1"
  lodash: "4.18.0"
  node-forge: "1.4.0"
  "picomatch@2.3.1": "4.0.4"
  "picomatch@4.0.3": "4.0.4"
  postcss: "8.5.23"
  shell-quote: "1.8.4"
  "xcode>uuid": "14.0.0"
  yaml: "2.8.3"
